package org.nbone.mvc.model;

// default package
// Generated 2013-8-5 21:27:22 by Hibernate Tools 3.2.4.GA

/**
 * WfAuth generated by hbm2java
 */
public class WfAuth implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3299791198275574457L;
	private Integer id;
	private String processId;
	private String processName;
	private String nodeId;
	private String nodeName;
	private String roleId;
	private String roleName;

	public WfAuth() {
	}

	public WfAuth(String processId, String processName, String nodeId,
			String nodeName, String roleId, String roleName) {
		this.processId = processId;
		this.processName = processName;
		this.nodeId = nodeId;
		this.nodeName = nodeName;
		this.roleId = roleId;
		this.roleName = roleName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	public String getProcessName() {
		return this.processName;
	}

	public void setProcessName(String processName) {
		this.processName = processName;
	}

	public String getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(String nodeId) {
		this.nodeId = nodeId;
	}

	public String getNodeName() {
		return this.nodeName;
	}

	public void setNodeName(String nodeName) {
		this.nodeName = nodeName;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

}
